FROM openjdk:11
LABEL maintainer="javaguides.net"
ADD target/springboot-backendsalarie-angular.jar springboot-backendsalarie-angular-demo.jar
ENTRYPOINT ["java","-jar","springboot-backendsalarie-angular-demo"]
